name: Create Release and Run CodeQL

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_number }}
        release_name: Release ${{ github.event.inputs.release_number }}
        body: "Release created for tag ${{ github.event.inputs.release_number }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run_codeql:
    name: Run CodeQL Analysis
    runs-on: windows-latest
    needs: create_release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.release_number }}

    - name: Install .NET Framework Developer Pack
      run: |
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          $Arguments = '/c', "$InstallPath", 'modify', '--installPath', "`"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise`"", '--add', 'Microsoft.Net.Component.4.8.1.SDK', '--quiet', '--norestart', '--nocache'
          Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore WebApplication1.sln
      
    - name: Build solution
      run: msbuild WebApplication1.sln -t:rebuild -property:Configuration=Release
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript,typescript'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
